### ISSUE TITLE
Register as a bower component

### ISSUE THREAD

**Issue by leolux** [kevinberonilla/jquery-quick-modal#1]
This is quite easy: http://bower.io/docs/creating-packages/#register

**Comment by kevinberonilla** [comment]
Thanks for that recommendation! Hopefully I did it all correctly. Updating the readme now.

**Comment by leolux** [comment]
I would change the "main" object and use the non-minified versions instead. It makes debugging during development easier and minification is a the task of a build tool and not the depedency itself. Nevertheless if someone prefers to use the minifed version the "main" value can be easily be overriden in the bower.json of every project.

**Comment by kevinberonilla** [comment]
Good catch, thanks!
