### ISSUE TITLE
I need to change the modal class.

### ISSUE THREAD

**Issue by graphicagenda** [kevinberonilla/jquery-quick-modal#2]
The framework I am using already claimed a modal class. Is there a way to invoke a new modal class that is not `class="modal"`

**Comment by kevinberonilla** [comment]
Currently, there isn't without hacking both the JS and CSS file. Something I should do (and really should have started out doing) is add prefixes to my classes in cases like these where collision can happen. I will start developing a version where all classes and ids used by the plugin utilize the `qm-` prefix. I will let you know when it's ready to try out; it will be available in the `development` branch soon. I will post updates here.

If you need an immediate solution, I would suggest not using the minified versions of the JS and CSS, and replace all instances of `.modal` to `.yourprefix-modal` in the CSS file and also prepend your prefix to lines `64` and `82` in the JS.

**Comment by kevinberonilla** [comment]
Hi @graphicagenda, the updated version with the new prefix is now available in the `development` branch (https://github.com/kevinberonilla/jquery-quick-modal/tree/development).

Please note that this is not an official release **yet**. I did some quick tests and everything is in order, though I'd like to do some full-pass tests before actually releasing it. You will need to update the `modal` class in your HTML to `qm-modal` and the `close-modal` class to `qm-close-modal`.

Let me know if you need any help with implementing this, or if you run into issues.

**Comment by kevinberonilla** [comment]
@graphicagenda, v2.0.0 on `master` has been released with the aforementioned changes. Please let me know if the new version solves your problem. If you absolutely need to use your own prefix, you can safely do a find and replace with `qm-`.

Additionally, I'm considering a future version using Sass to build the CSS dependencies so users can edit the source with their own prefix, as well as change a variable on the JS dependencies to handle the prefix updates on the JS side.
